import { motion } from "framer-motion";
import {
  Upload,
  Trophy,
  Medal,
  History,
  User,
  Settings,
  LogOut,
  BarChart3,
  Activity,
  Bell,
  Search,
  Brain,
  TrendingUp,
  AlertCircle,
} from "lucide-react";

import {
  Link,
  useNavigate,
} from "react-router-dom";

import {
  useEffect,
  useMemo,
  useState,
} from "react";

import { useAuth } from "../context/AuthContext";

export default function Dashboard() {
  const navigate = useNavigate();
  const { user, logout } = useAuth();

  /*
    Expected future backend response:

    {
      history: [
        {
          analysisId: "abc123",
          sport: "badminton",
          overallScore: 87,
          createdAt: "2026-08-22T10:30:00Z",
          status: "completed",
          metrics: [],
          suggestions: []
        }
      ]
    }

    No assessment data is generated by the frontend.
  */

  const [historyData, setHistoryData] = useState([]);

  const [loading, setLoading] =
    useState(true);

  const [error, setError] =
    useState(null);

  const [searchQuery, setSearchQuery] =
    useState("");

  const completedAnalyses = useMemo(() => {
    return historyData.filter(
      (item) =>
        item.status === "completed"
    );
  }, [historyData]);

  const totalUploads =
    historyData.length;

  const scores = completedAnalyses
    .map((item) =>
      Number(item.overallScore)
    )
    .filter(
      (score) =>
        !Number.isNaN(score)
    );

  const averageScore =
    scores.length > 0
      ? Math.round(
          scores.reduce(
            (sum, score) =>
              sum + score,
            0
          ) / scores.length
        )
      : null;

  const bestScore =
    scores.length > 0
      ? Math.max(...scores)
      : null;

  const sportsPlayed =
    new Set(
      historyData
        .map((item) =>
          item.sport
            ?.trim()
            ?.toLowerCase()
        )
        .filter(Boolean)
    ).size;
      /*
    Backend Integration Point

    Your teammate can replace this section with the actual API call.

    Example:
    GET /api/analysis/history

    Expected response:
    {
      history: [...]
    }
  */

  useEffect(() => {
    const loadDashboardData = async () => {
      try {
        setLoading(true);
        setError(null);

        /*
          Backend integration will go here.

          Example:

          const response = await fetch(
            "YOUR_BACKEND_API_URL/api/analysis/history",
            {
              headers: {
                Authorization: `Bearer ${user?.token}`,
              },
            }
          );

          if (!response.ok) {
            throw new Error(
              "Unable to load dashboard data"
            );
          }

          const data = await response.json();

          setHistoryData(
            Array.isArray(data.history)
              ? data.history
              : []
          );
        */

        setHistoryData([]);

      } catch (err) {

        console.error(
          "Dashboard data error:",
          err
        );

        setError(
          err.message ||
            "Unable to load dashboard data."
        );

        setHistoryData([]);

      } finally {

        setLoading(false);

      }
    };

    loadDashboardData();
  }, []);

  const stats = [
    {
      title: "Total Uploads",
      value: loading
        ? "..."
        : totalUploads,
      icon: Upload,
      color: "bg-blue-500",
    },
    {
      title: "Average Score",
      value: loading
        ? "..."
        : averageScore !== null
        ? `${averageScore}%`
        : "N/A",
      icon: Trophy,
      color: "bg-yellow-500",
    },
    {
      title: "Best Score",
      value: loading
        ? "..."
        : bestScore !== null
        ? `${bestScore}%`
        : "N/A",
      icon: Medal,
      color: "bg-green-500",
    },
    {
      title: "Sports Played",
      value: loading
        ? "..."
        : sportsPlayed,
      icon: Activity,
      color: "bg-red-500",
    },
  ];

  const recentUploads = useMemo(() => {
    return [...historyData]
      .sort((a, b) => {
        const firstDate =
          new Date(a.createdAt || 0);

        const secondDate =
          new Date(b.createdAt || 0);

        return secondDate - firstDate;
      })
      .slice(0, 3);
  }, [historyData]);

  const latestAnalysis =
    recentUploads.length > 0
      ? recentUploads[0]
      : null;

  const latestMetrics =
    latestAnalysis?.metrics &&
    Array.isArray(latestAnalysis.metrics)
      ? latestAnalysis.metrics
      : [];

  const latestSuggestions =
    latestAnalysis?.suggestions &&
    Array.isArray(
      latestAnalysis.suggestions
    )
      ? latestAnalysis.suggestions
      : [];

  const filteredUploads = useMemo(() => {
    const query =
      searchQuery.trim().toLowerCase();

    if (!query) {
      return recentUploads;
    }

    return recentUploads.filter((item) =>
      item.sport
        ?.toLowerCase()
        .includes(query)
    );
  }, [recentUploads, searchQuery]);

  const formatRelativeDate = (
    dateValue
  ) => {
    if (!dateValue) {
      return "Date unavailable";
    }

    const date =
      new Date(dateValue);

    if (
      Number.isNaN(
        date.getTime()
      )
    ) {
      return "Date unavailable";
    }

    return date.toLocaleDateString(
      undefined,
      {
        day: "2-digit",
        month: "short",
        year: "numeric",
      }
    );
  };

  const handleLogout = () => {
    logout?.();
    navigate("/");
  };

  return (
    <div className="flex min-h-screen bg-[#050505] text-white">

    {/* Sidebar */}

    <aside className="relative hidden min-h-screen w-72 shrink-0 border-r border-white/10 bg-black/80 backdrop-blur-xl lg:block">

      <div className="border-b border-white/10 p-8">

        <h1 className="text-3xl font-bold">
          SPORTSSCOUT
        </h1>

        <p className="mt-2 text-xs uppercase tracking-[4px] text-red-500">
          AI Dashboard
        </p>

      </div>

      <nav className="space-y-3 p-6">

        <Link
          to="/dashboard"
          className="flex items-center gap-4 rounded-2xl bg-red-600 px-5 py-4"
        >
          <BarChart3 size={22} />
          Dashboard
        </Link>

        {/* Upload should start with sport selection */}
        <Link
          to="/"
          className="flex items-center gap-4 rounded-2xl px-5 py-4 transition hover:bg-white/10"
        >
          <Upload size={22} />
          Upload Video
        </Link>

        <Link
          to="/history"
          className="flex items-center gap-4 rounded-2xl px-5 py-4 transition hover:bg-white/10"
        >
          <History size={22} />
          History
        </Link>

        <Link
          to="/profile"
          className="flex items-center gap-4 rounded-2xl px-5 py-4 transition hover:bg-white/10"
        >
          <User size={22} />
          Profile
        </Link>

        <button
          type="button"
          disabled
          className="flex w-full cursor-not-allowed items-center gap-4 rounded-2xl px-5 py-4 text-gray-500"
        >
          <Settings size={22} />
          Settings
        </button>

      </nav>

      <div className="absolute bottom-6 left-6 right-6">

        <button
          type="button"
          onClick={handleLogout}
          className="flex w-full items-center gap-4 rounded-2xl bg-red-600 px-5 py-4 font-semibold transition hover:bg-red-700"
        >
          <LogOut size={22} />
          Logout
        </button>

      </div>

    </aside>

    {/* Main Content */}

    <main className="min-w-0 flex-1 p-6 lg:p-10">

      {/* Header */}

      <div className="mb-10 flex flex-col justify-between gap-6 xl:flex-row xl:items-center">

        <div>

          <h1 className="text-4xl font-bold sm:text-5xl">
            Welcome Back{user?.name ? `, ${user.name}` : ""} 👋
          </h1>

          <p className="mt-3 text-gray-400">
            Track your AI sports performance and recent uploads.
          </p>

        </div>

        <div className="flex items-center gap-4">

          <div className="flex flex-1 items-center gap-3 rounded-full border border-white/10 bg-white/5 px-5 py-3 sm:min-w-[280px]">

            <Search
              size={18}
              className="shrink-0 text-gray-400"
            />

            <input
              type="text"
              value={searchQuery}
              onChange={(event) =>
                setSearchQuery(event.target.value)
              }
              placeholder="Search recent uploads..."
              className="min-w-0 w-full bg-transparent text-white outline-none placeholder:text-gray-500"
            />

          </div>

          <button
            type="button"
            disabled
            aria-label="Notifications unavailable"
            className="cursor-not-allowed rounded-full border border-white/10 p-4 text-gray-500"
          >
            <Bell size={20} />
          </button>

        </div>

      </div>

      {/* New Upload */}

      <Link to="/">

        <button
          type="button"
          className="mb-10 rounded-full bg-red-600 px-8 py-4 font-semibold transition hover:bg-red-700"
        >
          Upload New Video
        </button>

      </Link>

      {/* Loading State */}

      {loading && (

        <div className="mb-8 rounded-3xl border border-white/10 bg-white/[0.04] p-6 text-gray-400">
          Loading dashboard data...
        </div>

      )}

      {/* Error State */}

      {error && (

        <div className="mb-8 flex items-start gap-4 rounded-3xl border border-red-500/20 bg-red-500/10 p-6">

          <AlertCircle
            size={26}
            className="shrink-0 text-red-400"
          />

          <div>

            <h2 className="font-semibold text-red-300">
              Unable to Load Dashboard Data
            </h2>

            <p className="mt-2 text-gray-300">
              {error}
            </p>

          </div>

        </div>

      )}

      {/* Statistics */}

      <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
      {stats.map((item) => {

const Icon = item.icon;

return (

  <motion.div
    key={item.title}
    whileHover={{ y: -5 }}
    className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"
  >

    <div className="flex items-center justify-between">

      <div>

        <p className="text-sm uppercase tracking-[3px] text-gray-400">
          {item.title}
        </p>

        <h2 className="mt-4 text-4xl font-bold sm:text-5xl">
          {item.value}
        </h2>

      </div>

      <div
        className={`${item.color} rounded-2xl p-4`}
      >
        <Icon size={30} />
      </div>

    </div>

  </motion.div>

);

})}

</div>

{/* Dashboard Content */}

<div className="mt-12 grid gap-8 lg:grid-cols-2">

{/* Performance Summary */}

<div className="rounded-3xl border border-white/10 bg-white/[0.04] p-8">

<div className="mb-8 flex items-center gap-3">

  <TrendingUp
    size={30}
    className="text-red-500"
  />

  <div>

    <h2 className="text-2xl font-bold sm:text-3xl">
      Performance Summary
    </h2>

    <p className="mt-1 text-sm text-gray-500">
      Metrics from your latest completed assessment
    </p>

  </div>

</div>

{latestMetrics.length > 0 ? (

  <div className="space-y-7">

    {latestMetrics.map((metric) => {

      const value =
        Number(metric.value);

      const validValue =
        !Number.isNaN(value);

      return (

        <div
          key={
            metric.key ||
            metric.title
          }
        >

          <div className="mb-2 flex justify-between gap-4">

            <span className="capitalize text-gray-200">
              {metric.title ||
                metric.key ||
                "Metric"}
            </span>

            <span className="font-semibold text-white">
              {validValue
                ? `${value}%`
                : "N/A"}
            </span>

          </div>

          <div className="h-3 overflow-hidden rounded-full bg-zinc-800">

            <motion.div
              initial={{
                width: 0,
              }}
              animate={{
                width: validValue
                  ? `${Math.min(
                      Math.max(
                        value,
                        0
                      ),
                      100
                    )}%`
                  : "0%",
              }}
              transition={{
                duration: 0.8,
              }}
              className="h-full rounded-full bg-red-600"
            />

          </div>

        </div>

      );

    })}

  </div>

) : (

  <div className="rounded-2xl border border-white/10 bg-black/20 p-8 text-center">

    <Activity
      size={38}
      className="mx-auto text-gray-500"
    />

    <h3 className="mt-5 text-xl font-semibold">
      No Performance Metrics Available
    </h3>

    <p className="mt-3 leading-7 text-gray-400">
      Your performance metrics will appear here after a completed
      video analysis provides assessment data.
    </p>

  </div>

)}

</div>

{/* Recent Uploads */}

<div className="rounded-3xl border border-white/10 bg-white/[0.04] p-8">

<div className="mb-8 flex items-center justify-between gap-4">

  <div>

    <h2 className="text-2xl font-bold sm:text-3xl">
      Recent Uploads
    </h2>

    <p className="mt-1 text-sm text-gray-500">
      Your latest analyzed videos
    </p>

  </div>

  <Link
    to="/history"
    className="text-sm font-semibold text-red-400 transition hover:text-red-300"
  >
    View All
  </Link>

</div>

{filteredUploads.length > 0 ? (

  <div className="space-y-5">

    {filteredUploads.map((item) => (

      <motion.button
        type="button"
        key={item.analysisId}
        whileHover={{
          scale: 1.01,
        }}
        onClick={() =>
          item.status === "completed" &&
          navigate("/report", {
            state: {
              analysisId:
                item.analysisId,
            },
          })
        }
        disabled={
          item.status !== "completed"
        }
        className={`flex w-full items-center justify-between rounded-2xl border border-white/10 bg-black/20 p-5 text-left transition ${
          item.status === "completed"
            ? "hover:border-red-500/40"
            : "cursor-not-allowed opacity-60"
        }`}
      >

        <div>

          <h3 className="text-xl font-semibold capitalize">
            {item.sport ||
              "Unknown Sport"}
          </h3>

          <p className="mt-2 text-gray-400">
            {formatRelativeDate(
              item.createdAt
            )}
          </p>

          <p className="mt-1 text-xs capitalize text-gray-500">
            {item.status ||
              "Unknown"}
          </p>

        </div>

        <div className="text-right">

          <p className="text-sm uppercase tracking-[2px] text-gray-500">
            Score
          </p>

          <p className="mt-1 text-3xl font-bold text-red-500">

            {item.overallScore !==
              undefined &&
            item.overallScore !==
              null
              ? `${item.overallScore}%`
              : "N/A"}

          </p>

        </div>

      </motion.button>

    ))}

  </div>

) : (

  <div className="rounded-2xl border border-white/10 bg-black/20 p-8 text-center">

    <Upload
      size={38}
      className="mx-auto text-gray-500"
    />

    <h3 className="mt-5 text-xl font-semibold">
      No Recent Uploads
    </h3>

    <p className="mt-3 leading-7 text-gray-400">
      Upload a sports performance video to begin your first AI
      assessment.
    </p>

  </div>

)}

</div>

</div>
        {/* Bottom Section */}

        <div className="mt-12 grid gap-8 lg:grid-cols-2">

          {/* AI Recommendation */}

          <motion.div
            whileHover={{ y: -5 }}
            className="rounded-3xl border border-red-500/20 bg-red-600/10 p-8"
          >

            <div className="mb-6 flex items-center gap-3">

              <Brain
                size={30}
                className="text-red-500"
              />

              <div>

                <h2 className="text-2xl font-bold sm:text-3xl">
                  AI Recommendation
                </h2>

                <p className="mt-1 text-sm text-gray-400">
                  Suggestions from your latest completed assessment
                </p>

              </div>

            </div>

            {latestSuggestions.length > 0 ? (

              <ul className="space-y-4 text-gray-200">

                {latestSuggestions.map(
                  (suggestion, index) => (

                    <li
                      key={index}
                      className="flex gap-3 leading-7"
                    >

                      <span className="text-red-400">
                        •
                      </span>

                      <span>
                        {suggestion}
                      </span>

                    </li>

                  )
                )}

              </ul>

            ) : (

              <div className="rounded-2xl border border-white/10 bg-black/20 p-6">

                <p className="leading-7 text-gray-400">

                  AI recommendations will appear here after a completed
                  assessment provides personalized improvement suggestions.

                </p>

              </div>

            )}

          </motion.div>

          {/* Quick Actions */}

          <motion.div
            whileHover={{ y: -5 }}
            className="rounded-3xl border border-white/10 bg-white/[0.04] p-8"
          >

            <h2 className="mb-8 text-2xl font-bold sm:text-3xl">
              Quick Actions
            </h2>

            <div className="grid gap-4">

              <Link to="/">

                <button
                  type="button"
                  className="flex w-full items-center gap-4 rounded-2xl bg-red-600 px-6 py-5 font-semibold transition hover:bg-red-700"
                >

                  <Upload size={22} />

                  Upload New Video

                </button>

              </Link>

              <Link to="/history">

                <button
                  type="button"
                  className="flex w-full items-center gap-4 rounded-2xl border border-white/10 px-6 py-5 font-semibold transition hover:bg-white/10"
                >

                  <History size={22} />

                  Upload History

                </button>

              </Link>

              {latestAnalysis &&
              latestAnalysis.status ===
                "completed" ? (

                <button
                  type="button"
                  onClick={() =>
                    navigate("/report", {
                      state: {
                        analysisId:
                          latestAnalysis.analysisId,
                      },
                    })
                  }
                  className="flex w-full items-center gap-4 rounded-2xl border border-white/10 px-6 py-5 font-semibold transition hover:bg-white/10"
                >

                  <Trophy size={22} />

                  View Latest Report

                </button>

              ) : (

                <button
                  type="button"
                  disabled
                  className="flex w-full cursor-not-allowed items-center gap-4 rounded-2xl border border-white/10 px-6 py-5 text-gray-500"
                >

                  <Trophy size={22} />

                  Latest Report Unavailable

                </button>

              )}

            </div>

          </motion.div>

        </div>

      </main>

    </div>
  );
}