import { motion } from "framer-motion";
import {
  History,
  Trophy,
  Calendar,
  Search,
  Eye,
  Download,
  Upload,
  AlertCircle,
} from "lucide-react";
import {
  Link,
  useNavigate,
} from "react-router-dom";
import { useMemo, useState } from "react";

export default function HistoryPage() {
  const navigate = useNavigate();

  /*
    Future backend response example:

    {
      history: [
        {
          analysisId: "abc123",
          sport: "badminton",
          overallScore: 87,
          createdAt: "2026-08-22T10:30:00Z",
          status: "completed",
          downloadUrl: "..."
        }
      ]
    }

    No history entries or scores are generated by the frontend.
  */
  const [historyData] = useState([]);

  const [searchQuery, setSearchQuery] =
    useState("");

  const filteredHistory = useMemo(() => {
    const query =
      searchQuery.trim().toLowerCase();

    if (!query) {
      return historyData;
    }

    return historyData.filter((item) =>
      item.sport
        ?.toLowerCase()
        .includes(query)
    );
  }, [historyData, searchQuery]);

  const completedAnalyses =
    historyData.filter(
      (item) =>
        item.status === "completed"
    );

  const bestScore =
    completedAnalyses.length > 0
      ? Math.max(
          ...completedAnalyses
            .map((item) =>
              Number(item.overallScore)
            )
            .filter(
              (score) =>
                !Number.isNaN(score)
            )
        )
      : null;

  const latestAnalysis =
    historyData.length > 0
      ? historyData[0]
      : null;

  const formatDate = (dateValue) => {
    if (!dateValue) {
      return "Not available";
    }

    const date = new Date(dateValue);

    if (Number.isNaN(date.getTime())) {
      return "Not available";
    }

    return date.toLocaleDateString(
      undefined,
      {
        day: "2-digit",
        month: "short",
        year: "numeric",
      }
    );
  };

  const handleViewReport = (item) => {
    navigate("/report", {
      state: {
        analysisId: item.analysisId,
      },
    });
  };

  return (
    <section className="min-h-screen bg-[#050505] px-6 py-10 text-white">
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="mx-auto max-w-7xl"
      ></motion.div>
              {/* Header */}
              <div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-center">

<div>

  <h1 className="text-4xl font-bold sm:text-5xl">
    Upload History
  </h1>

  <p className="mt-3 text-gray-400">
    View all previously analyzed sports videos.
  </p>

</div>

<div className="flex h-20 w-20 items-center justify-center rounded-full bg-red-600">
  <History size={38} />
</div>

</div>

{/* Search */}
<div className="mt-10 flex items-center gap-3 rounded-full border border-white/10 bg-white/5 px-6 py-4">

<Search
  size={20}
  className="shrink-0 text-gray-400"
/>

<input
  type="text"
  value={searchQuery}
  onChange={(event) =>
    setSearchQuery(event.target.value)
  }
  placeholder="Search by sport..."
  className="w-full bg-transparent text-white outline-none placeholder:text-gray-500"
/>

</div>

{/* Statistics */}
<div className="mt-10 grid gap-6 md:grid-cols-3">

{/* Total Uploads */}
<div className="rounded-3xl border border-white/10 bg-white/[0.04] p-8">

  <Upload
    size={35}
    className="text-red-500"
  />

  <h2 className="mt-5 text-4xl font-bold">

    {historyData.length}

  </h2>

  <p className="mt-2 text-gray-400">
    Total Uploads
  </p>

</div>

{/* Best Score */}
<div className="rounded-3xl border border-white/10 bg-white/[0.04] p-8">

  <Trophy
    size={35}
    className="text-yellow-500"
  />

  <h2 className="mt-5 text-4xl font-bold">

    {bestScore !== null
      ? `${bestScore}%`
      : "N/A"}

  </h2>

  <p className="mt-2 text-gray-400">
    Best Score
  </p>

</div>

{/* Last Upload */}
<div className="rounded-3xl border border-white/10 bg-white/[0.04] p-8">

  <Calendar
    size={35}
    className="text-green-500"
  />

  <h2 className="mt-5 text-2xl font-bold">

    {latestAnalysis
      ? formatDate(
          latestAnalysis.createdAt
        )
      : "N/A"}

  </h2>

  <p className="mt-2 text-gray-400">
    Last Upload
  </p>

</div>

</div>

{/* History List */}
<div className="mt-12">
            {/* Empty History State */}
            {historyData.length === 0 && (

<div className="rounded-3xl border border-white/10 bg-white/[0.04] p-10 text-center">

  <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-red-500/10">
    <AlertCircle
      size={32}
      className="text-red-400"
    />
  </div>

  <h2 className="mt-6 text-2xl font-semibold">
    No Upload History Available
  </h2>

  <p className="mx-auto mt-3 max-w-xl leading-7 text-gray-400">
    Your previously analyzed sports videos will appear here after
    the SportsScout backend stores your completed analyses.
  </p>

  <Link
    to="/dashboard"
    className="mt-8 inline-flex rounded-full bg-red-600 px-7 py-3 font-semibold transition hover:bg-red-700"
  >
    Go to Dashboard
  </Link>

</div>

)}

{/* No Search Results */}
{historyData.length > 0 &&
filteredHistory.length === 0 && (

<div className="rounded-3xl border border-white/10 bg-white/[0.04] p-10 text-center">

  <Search
    size={36}
    className="mx-auto text-gray-500"
  />

  <h2 className="mt-5 text-2xl font-semibold">
    No Matching Uploads Found
  </h2>

  <p className="mt-3 text-gray-400">
    Try searching for a different sport.
  </p>

</div>

)}

{/* Real History Cards */}
{filteredHistory.length > 0 && (

<div className="space-y-6">

  {filteredHistory.map((item) => (

    <motion.div
      key={item.analysisId}
      whileHover={{
        y: -5,
        scale: 1.01,
      }}
      className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 backdrop-blur-xl sm:p-8"
    >

      <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">

        <div>

          <h2 className="text-2xl font-bold capitalize sm:text-3xl">
            {item.sport || "Unknown Sport"}
          </h2>

          <p className="mt-3 text-gray-400">
            Uploaded on {formatDate(item.createdAt)}
          </p>

          <p className="mt-2 text-sm capitalize text-gray-500">
            Status: {item.status || "Unknown"}
          </p>

        </div>

        <div className="flex flex-wrap items-center gap-4 sm:gap-6">

          <div>

            <p className="text-sm uppercase tracking-[3px] text-gray-400">
              Score
            </p>

            <h3 className="mt-2 text-3xl font-bold text-red-500 sm:text-4xl">

              {item.overallScore !== undefined &&
              item.overallScore !== null
                ? `${item.overallScore}%`
                : "N/A"}

            </h3>

          </div>

          <button
            onClick={() =>
              handleViewReport(item)
            }
            disabled={
              item.status !== "completed"
            }
            className={`flex items-center gap-3 rounded-full px-6 py-3 font-semibold transition ${
              item.status === "completed"
                ? "bg-red-600 hover:bg-red-700"
                : "cursor-not-allowed bg-gray-700 text-gray-400"
            }`}
          >

            <Eye size={20} />

            View Report

          </button>

          {item.downloadUrl ? (

            <a
              href={item.downloadUrl}
              target="_blank"
              rel="noreferrer"
              className="flex items-center gap-3 rounded-full border border-white/10 px-6 py-3 font-semibold transition hover:bg-white/10"
            >

              <Download size={20} />

              Download

            </a>

          ) : (

            <button
              disabled
              className="flex cursor-not-allowed items-center gap-3 rounded-full border border-white/10 px-6 py-3 font-semibold text-gray-500"
            >

              <Download size={20} />

              Download Unavailable

            </button>

          )}

        </div>

      </div>

    </motion.div>

  ))}

</div>

)}
          {/* Back to Dashboard */}

          <div className="mt-14 text-center">

            <Link
              to="/dashboard"
              className="inline-flex rounded-full bg-red-600 px-10 py-4 text-lg font-semibold transition hover:bg-red-700"
            >
              Back to Dashboard
            </Link>

          </div>

        </div>
      </motion.div>
    </section>
  );
}